<div class="content-header">
    AJAX DEMO
    <p class="form-buttons">
    	<button name="" onclick = "javascript:openMyPopup()">POP UP</button>
    </p>
</div>

<script type="text/javascript">
    function openMyPopup() {

        var url = '<?php echo $this->getUrl('adminhtml/dashboard/index') ?>';
 		//alert(url);
        /*if (jQuery('browser_window') &amp;&amp; typeof(Windows) != 'undefined') {
            Windows.focus('browser_window');
            return;
        }*/

        var dialogWindow = Dialog.info(null, {
            closable:true,
            resizable:false,
            draggable:true,
            className:'magento',
            windowClassName:'popup-window',
            title:'Test popup Dialog',
            top:50,
            width:300,
            height:150,
            zIndex:1000,
            recenterAuto:false,
            hideEffect:Element.hide,
            showEffect:Element.show,
            id:'browser_window',
            url:url,
            onClose:function (param, el) {
                alert('onClose');
            }
        });
    }
 
    function closePopup() {
        Windows.close('browser_window');
    }
 
</script>